### ISSUE TITLE
More info about Selectors and SectionsToSkip

### ISSUE THREAD

**Issue by ghost** [SR-G/watchthatpage#7]
Thank you for this tool. I have it running in the meantime with 3 cron jobs (hourly, daily, weekly).

The readme is also quite comprehensive, but I'm still unsure which possibilities Selectors and SectionsToSkip do offer. The only example of Selectors is this:

`  "Selectors" : {
	"http://www.fiio.me/forum.php?mod=viewthread&tid=39932" : { "Selector" : "td[id=postmessage_105396]", "SelectorsToSkip" : [ "ignore_js_op" ] }
  },`

Is there any in-depth documentation for Selectors and SectionsToSkip?

Thanks

**Comment by SR-G** [comment]
Hello.

The implemented are really just regular CSS selectors (as available in other languages, javascript, and so on)..

Here this golang implementation is coming from the golang additional library "[andybalholm/cascadia](https://godoc.org/github.com/andybalholm/cascadia)".

You can find additional examples / explanations in various regular areas like : 
- https://www.w3schools.com/cssref/css_selectors.asp
- http://butlerccwebdev.net/support/css-selectors-cheatsheet.html
(most should work)

It's of course the same syntax here for "Selector" and "SelectorsToSkip". I had a few situation for which it was easier to filter (main "Selector" entry) and then to exclude additional patterns (SelectorsToSkip) (which can of course be empty if not needed).

**Comment by ghost** [comment]
Great, thank you. Also for your quick answer.

Very helpful stuff, will dig into it.
