### ISSUE TITLE
Discord addition

### ISSUE THREAD

**Issue by vladdoster** [SR-G/watchthatpage#8]
Great work here.

Would you be open to reviewing and possibly merging a PR to add discord notifications? or should I just keep it in my fork?

**Comment by SR-G** [comment]
Hello.
Sure, send it as a PR, i'll review / merge it (if it's somehow optional / configurable and not mandatory for everyone).

**Comment by vladdoster** [comment]
Awesome. Yes it would be opt in. And I assume it would need to be such that a user can receive both email and discord?

**Comment by SR-G** [comment]
Yes, the best would be to just have an extra (optional) configuration like : 
```
"NotificationDiscord" : { 
	"discordServer" : "http://...",
	"discordCredentials" : "",
	"template" : "WatchThatPage results : {{ .NbDiff }} page(s) changed"
  }
```
(note : i have no idea how discord notification is working about API + credentials, so this is obviously just an example)

And indeed, from a code point of view, either "NotificationMail", either "NotificationDiscord", either both, can be activated.
